name: Arduino ESP32 Build

on:
  push:
    branches: ["main", "v*"]
  pull_request:
    branches: ["main", "v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LIB_DIR_NAME: AI_VOX
      ARDUINO_CLI_DIR: ${{github.workspace}}/arduino_cli
      ARDUINO_CLI_CONFIG_DIR: ${{github.workspace}}/arduino_cli_config
      ARDUINO_USER_DIR: ${{github.workspace}}/arduino_user
      AI_VOX_VERSION: "v1.3.1"
    strategy:
      matrix:
        example: ["esp32/ai_vox_engine_us04_dht11_photosensitive_display_lcd_mcp", "esp32/ai_vox_engine_us04_dht11_photosensitive_display_oled_mcp"]

    steps:
      - name: Checkout examples repository
        uses: actions/checkout@v4
      
      - name: download arduino cli
        run: curl -L -o arduino-cli.tar.gz https://github.com/arduino/arduino-cli/releases/download/v1.2.0/arduino-cli_1.2.0_Linux_64bit.tar.gz
      
      - name: install arduino cli
        run: |
          mkdir -p ${ARDUINO_CLI_DIR}
          tar -zxvf arduino-cli.tar.gz -C ${ARDUINO_CLI_DIR}
      
      - name: test arduino cli
        run: ${ARDUINO_CLI_DIR}/arduino-cli -v
      
      - name: setup arduino-cli
        run: |
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} config init
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} config set directories.user ${ARDUINO_USER_DIR}
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} config set library.enable_unsafe_install true
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} config dump
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} core install esp32:esp32@3.2.0
      
      - name: install lib lvgl@9.2.2
        run: |
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} lib install "lvgl@9.2.2"
      
      - name: install lib DHT_sensor_library
        run: |
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} lib install "DHT sensor library@1.4.6"
      
      - name: Install AI_VOX Library from GitHub (v1.3.1)
        run: |
          echo "Installing AI_VOX library version ${AI_VOX_VERSION}"
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} lib install --git-url https://github.com/nulllaborg/ai_vox.git#${AI_VOX_VERSION}
      
      - name: Verify installed libraries
        run: |
          echo "Installed libraries:"
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} lib list
      
      - name: compile
        run: |
          echo "Compiling ${GITHUB_WORKSPACE}/${{matrix.example}}"
          ${ARDUINO_CLI_DIR}/arduino-cli --config-dir ${ARDUINO_CLI_CONFIG_DIR} compile --fqbn esp32:esp32:esp32 "${GITHUB_WORKSPACE}/${{matrix.example}}" -j 0 --warnings all --board-options PartitionScheme=huge_app --build-property "build.extra_flags=-Wall -Werror" --log --clean -v